# -*- coding: utf-8 -*-
"""Regenerate src/fonts.css and public/fonts/*.woff2 from Google Fonts.

Self-hosting still starts from Google's own CSS endpoint -- it is the
correctly-hinted, already-subsetted source of truth for which glyphs live in
which file. What changes is that the site then serves those files itself
instead of sending every visitor's browser to fonts.googleapis.com and
fonts.gstatic.com first, which is two DNS + TLS round trips before a single
glyph can paint.

Filtered to the `latin` and `latin-ext` unicode-range subsets only. This site
has no Cyrillic, Greek, Vietnamese or Devanagari content; latin-ext is kept
because it covers the accented Western characters a name field can contain
("Renée", "Müller") that plain `latin` does not.

    python scripts/fetch-fonts.py

Re-run whenever FAMILIES below changes to match a real edit to the font
weights index.html links (it no longer links anything -- FAMILIES here and
the src url() list in fonts.css are the single source of truth now).
"""
import json
import os
import re
import urllib.request

FAMILIES = "family=Rajdhani:wght@400;500;600;700&family=Figtree:ital,wght@0,300..900;1,300..900&family=Newsreader:ital,wght@0,200..800;1,200..800&family=IBM+Plex+Mono:wght@400;500&family=Amaranth:ital@0;1"
CSS_ENDPOINT = f"https://fonts.googleapis.com/css2?{FAMILIES}&display=swap"
# A modern desktop UA is required -- Google serves woff2 only to UAs it
# recognises as supporting it; curl's default UA gets legacy ttf/eot.
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

FAMILY_SLUG = {"Rajdhani": "rajdhani", "Figtree": "figtree", "Newsreader": "newsreader", "IBM Plex Mono": "ibm-plex-mono", "Amaranth": "amaranth"}

FACE_RE = re.compile(
    r"font-family:\s*'([^']+)';\s*"
    r"font-style:\s*(\w+);\s*"
    r"font-weight:\s*([\d\s]+);\s*"
    r"font-display:\s*swap;\s*"
    r"src:\s*url\(([^)]+)\)\s*format\('woff2'\);\s*"
    r"unicode-range:\s*([^;]+);",
    re.S,
)

HERE = os.path.dirname(os.path.abspath(__file__))
FONTS_OUT = os.path.join(HERE, "..", "public", "fonts")
# public/, not src/: CRA's css-loader resolves a bare url(/fonts/...) inside
# an *imported* stylesheet as a webpack module path, not a browser URL, and
# fails the build outright. Living in public/ and being <link>ed from
# index.html (the same reason theme-boot.js lives there) means the browser
# resolves the path against the real served origin instead.
CSS_OUT = os.path.join(HERE, "..", "public", "fonts.css")


def main():
    req = urllib.request.Request(CSS_ENDPOINT, headers={"User-Agent": UA})
    css = urllib.request.urlopen(req, timeout=20).read().decode("utf-8")

    blocks = re.split(r"(?=/\* )", css)
    kept = [b for b in blocks if b.strip().startswith("/* latin") and "@font-face" in b]

    os.makedirs(FONTS_OUT, exist_ok=True)
    results = []
    for b in kept:
        m = FACE_RE.search(b)
        if not m:
            continue
        family, style, weight, url, urange = m.groups()
        weight = weight.strip().replace(" ", "-")
        subset = "ext" if "latin-ext" in b else "latin"
        fname = f"{FAMILY_SLUG[family]}-{weight}-{style}-{subset}.woff2"

        data = urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=20).read()
        with open(os.path.join(FONTS_OUT, fname), "wb") as f:
            f.write(data)
        results.append({"family": family, "style": style, "weight": weight, "file": fname, "unicodeRange": urange.strip()})
        print(f"{fname}: {len(data)} bytes")

    header = (
        "/* Self-hosted, not linked from fonts.googleapis.com/fonts.gstatic.com.\n"
        " * Generated by scripts/fetch-fonts.py -- do not hand-edit the font\n"
        " * list here without also updating FAMILIES in that script.\n"
        " *\n"
        " * Filtered to the latin + latin-ext subsets only (this site has no\n"
        " * non-Western content), downloaded from the woff2 URLs Google serves\n"
        " * for a modern browser UA.\n"
        " */\n\n"
    )
    with open(CSS_OUT, "w", encoding="utf-8") as out:
        out.write(header)
        for r in results:
            out.write("@font-face {\n")
            out.write(f"  font-family: '{r['family']}';\n")
            out.write(f"  font-style: {r['style']};\n")
            out.write(f"  font-weight: {r['weight'].replace('-', ' ')};\n")
            out.write("  font-display: swap;\n")
            out.write(f"  src: url(\"/fonts/{r['file']}\") format(\"woff2\");\n")
            out.write(f"  unicode-range: {r['unicodeRange']};\n")
            out.write("}\n\n")

    total = sum(len(open(os.path.join(FONTS_OUT, r["file"]), "rb").read()) for r in results)
    print(f"\n{len(results)} files, {total / 1024:.1f} KB total -> {CSS_OUT}")


if __name__ == "__main__":
    main()
